version: '5.0.2'

services:
  db:
    image: mariadb:latest
    container_name: ram-ms-logger-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ram_password
      MARIADB_DATABASE: ram-ms-logger-db
      MARIADB_USER: user
      MARIADB_PASSWORD: ram_password
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
